version: '2'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ddr533/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media
  frontend:
    image: ddr533/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: ddr533/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/var/www/media

